create table sensor(
                       id int generated by default as identity ,
                       name varchar primary key unique not null
);

create table measurement(
                            id int generated by default as identity primary key ,
                            value double precision not null ,
                            raining boolean not null,
                            sensor_name varchar references sensor(name),
                            created_at timestamp
)