create table sensor(
                       sensor_id int generated by default as identity primary key,
                       name varchar  unique not null
);

create table measurement(
                            measurement_id int generated by default as identity primary key ,
                            value double precision not null ,
                            raining boolean not null,
                            sensor varchar references sensor(name),
                            created_at timestamp not null
)